---
- name: INSTALLING A REQUIRED PACKAGES
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"
  notify: restart postfix

- name: SETTING A HOSTNAME OF MAIL SERVER
  hostname:
    name: "{{ mail_server_hostname }}"

- name: CREATING A /etc/postfix/main.cf file
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify: restart postfix

- name: STARTING A FIREWALLD
  service:
    name: firewalld
    state: restarted
    enabled: true
  notify: config firewall rules

- name: SELINUX
  selinux:
    policy: targeted
    state: permissive
