---
- name: Installing a python3-pip module
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
    - mod_ssl

- name: Installing a cryptography module
  ansible.builtin.pip:
    name: cryptography

- name: Generating a private key
  community.crypto.openssl_privatekey:
    path: "{{ ssl_key_path }}"
    mode: "0640"
    type: RSA
    size: 2048
    state: present

- name: Generating a Certificate Signing Request(CSR) for self signed certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ ssl_key_path }}"
    common_name: "{{ domain }}"
  register: csr

- name: Generating a self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ ssl_cert_path }}"
    privatekey_path: "{{ ssl_key_path }}"
    csr_content: "{{ csr.csr }}"
    provider: selfsigned
    selfsigned_not_after: "+365d"
    mode: "0644"
    state: present
